// packages/frontend/src/App.svelte
<script lang="ts">
  import Reset from "./config/Reset.svelte";
  import Theme from "./config/Theme.svelte";
  import AppBar from "./components/AppBar.svelte";
  import Drawer from "./components/Drawer.svelte";
  import Spinner from "./components/Spinner.svelte";
  import Button from "./components/Button.svelte";
  import Router from "./components/routing/Router.svelte";
  import Route from "./components/routing/Route.svelte";
  import Login from "./content/Login.svelte";
  import Sidebar from "./content/Sidebar.svelte";
  import SourcesPage from "./content/sources/SourcesPage.svelte";
  import { checkLogin, isLoggedIn, logout } from "./auth";
  import { t } from "./lang";

  let open = false;
  const handleClose = () => {
    open = false;
  };

  $: if (!$isLoggedIn) {
    sessionStorage.setItem("intended-route", window.location.pathname);
    history.pushState("", "", "/login");
  } else {
    const intended = sessionStorage.getItem("intended-route");
    sessionStorage.removeItem("intended-route");
    history.pushState("", "", intended || "/");
  }
</script>

<Reset />
<Theme />

<main>
  {#await checkLogin()}
    <div class="centered">
      <Spinner />
    </div>
  {:then _}
    <Router>
      {#if $isLoggedIn}
        <AppBar on:menuclick={() => (open = !open)} />

        <Drawer {open} on:close={handleClose}>
          <Sidebar on:close={handleClose} />
        </Drawer>

        <Button variant="tonal" on:click={logout}>Logout</Button>

        <Route path="/settings" title={$t("title.settings")}>
          <Button
            variant="text"
            on:click={() => history.pushState("", "", "/")}
          >
            Home
          </Button>
          (settings)
        </Route>

        <Route path="/sources" title={$t("title.sources")}>
          <SourcesPage />
        </Route>

        <Route path="/" fallback>main page</Route>
      {:else}
        <Route path="/login" title={$t("title.login")}>
          <Login />
        </Route>
      {/if}
    </Router>
  {/await}
</main>

<style lang="sass">
  :global(body)
    background-color: var(--color-background)

  .centered
    width: 100vw
    height: 100vh
    display: flex
    align-items: center
    justify-content: center
</style>

// packages/app/src/App.tsx
import { createSignal, Match, Switch } from "solid-js";
import { logout, userData } from "./auth";
import { navigate } from "./location";
import { t } from "./lang";
import { Drawer, Route, Router, Spinner } from "./components";
import Login from "./core/Login";
import SourceList from "./domains/sources/SourceList";
import Redirect from "./components/redirect/Redirect";
import {Suspense} from "solid-js/web";

export default function App() {
  const [isOpen, setOpen] = createSignal(false);

  return (
    <Router>
      <Switch>
        <Match when={userData.loading}>
          <Spinner />
        </Match>

        <Match when={userData()?.isLoggedIn}>
          <Route path="/">
            <div>
              <button onClick={() => logout()}>logout</button>
              <button onClick={() => setOpen(true)}>open</button>
              <button onClick={() => navigate("/sources")}>sources</button>
              <Drawer open={isOpen()} onClose={() => setOpen(false)}>drawer</Drawer>
            </div>
          </Route>

          <Route path="/sources" title={t("title.sources")}>
            <button onClick={() => navigate("/")}>root</button>

            <Suspense fallback={<Spinner />}>
              <SourceList />
            </Suspense>
          </Route>

          <Route path={/^\/.*/}>
            <Redirect to="/" />
          </Route>
        </Match>

        <Match when={!userData()?.isLoggedIn}>
          <Route path="/login" title={t("title.login")}>
            <Login />
          </Route>

          <Route path={/^\/.*/}>
            {() => {
              sessionStorage.setItem("intended-route", window.location.pathname);
              return <Redirect to="/login" />;
            }}
          </Route>
        </Match>
      </Switch>
    </Router>
  );
}
