// packages/app/src/domains/sources/SourceList.tsx
import { createResource, For } from "solid-js";
import gql from "graphql-tag";
import { createQuery } from "../../graphql";
import { Card } from "../../components";
import { SourcesQuery, SourcesQueryVariables } from "../../generated/graphql";
import "./SourceList.sass";

const fetchSources = createQuery<SourcesQuery, SourcesQueryVariables>(
  gql`
    query Sources {
      sources {
        totalCount
        pageInfo {
          startCursor
          endCursor
          hasPreviousPage
          hasNextPage
        }
        edges {
          cursor
          node {
            id
            type
            title
            added
            lastUpdate
            url
            faviconUrl
          }
        }
      }
    }
  `
);

export interface SourceListProps {}

export default function SourceList() {
  const [sources] = createResource(fetchSources);

  return (
    <div class="source-list">
      total: {sources()?.sources.totalCount}
      <For each={sources()?.sources.edges}>
        {({ node }) => (
          <Card>
            <div class="image">
              <img src={node.faviconUrl} alt="icon" />
            </div>

            <div class="info">
              <h2 class="typography-headline-small">{node.title}</h2>

              <span>(via {node.type})</span>
              <span>at {node.url}</span>
              <span>added {node.added}</span>
            </div>
          </Card>
        )}
      </For>
    </div>
  );
}

// packages/frontend/src/content/sources/SourceList.svelte
<script lang="ts">
  import { gql } from "graphql-tag";
  import Spinner from "../../components/Spinner.svelte";
  import Card from "../../components/Card.svelte";
  import { query } from "../../graphql";
  import {
    SourceListQuery,
    SourceListQueryVariables,
  } from "../../generated/graphql";

  const sources = query<SourceListQuery, SourceListQueryVariables>(gql`
    query SourceList {
      sources {
        totalCount
        pageInfo {
          startCursor
          endCursor
          hasPreviousPage
          hasNextPage
        }
        edges {
          cursor
          node {
            id
            type
            title
            uri
            added
            lastUpdate
          }
        }
      }
    }
  `);
</script>

{#await sources}
  <Spinner />
{:then data}
  <ul class="list">
    {#each data.sources.edges as source}
      <li>
        <Card>
          <span class="typography-headline-medium">{source.node.title}</span>
          <span>(via {source.node.type})</span>
          <span>at {source.node.uri}</span>
          <span>added {source.node.added}</span>
        </Card>
      </li>
    {/each}
  </ul>
{:catch err}
  <div>
    Error: {err.message}
  </div>
{/await}

<style lang="sass">
  .list
    margin: 0
    padding: 0
</style>
